version: '3.9'
services:
  bingo-api:
    build:
      context: ..
    image: oot-bingo-api
    ports:
        - "13443:3000"
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true
